#!/bin/bash

if [ $# -eq 0 ]
  then
    echo "Expected arguments, please check the help of this aplication : initdev –help"
    exit 1
fi

if [ $# -eq 1 ]
  then
    if [[ $1 == "-help" ]]; then
        echo " — Name : initdev c'est une  application quelle a un role de crée crée une arborecence ou les paramatre d'entrer sont le nom de votre application et en  le type du langage qu'on va utiliser plus le type de license  .
            — Syntax : ./initdev <nom-project> <type-de-langage ou type de license> .
            — args : -C :si on utilise le   langage c
                     -PY : si on utilise le  langage python
		     -C++ : si on utilise le langage c ++
		     -CPP :si on utilise le  langage cpp
                     -Latex : si on va utilisé un fichier de type la latex.
            — author : boudjerda djamel eddine   email : djamel_eddine_boudjerda@outlook.fr."
       else
       
        mkdir -p $1/{bin,gitignores,sources,}
        touch $1/license
        touch $1/makefile
	 touch $1/main
        touch $1/install.sh
        exit 0
       fi
       fi

    mkdir -p $1/{bin,gitignores,sources}
    touch $1/makefile
    touch $1/install.sh
     touch $1/LICENSE
    case "$2" in
        "-C") cp ./sources/main.c $1/main.c
        ;;
        "-C++") cp ./sources/main.cpp $1/main.cpp
        ;;
        "-CPP") cp ./sources/main.cpp $1/main.cpp
        ;;
        "-Py") cp ./sources/main.py $1/main.py
        ;;
        "-Latex") cp ./sources/latexMin.tex $1/main.tex
        ;;
        "-BEAMER") cp ./sources/beamer.tex $1/main.tex
        ;;
        "-GPL") cp ./licenses/GPL $1/LICENSE
	;;
	"-MIT") cp ./licenses/MIT $1/LICENSE
 	;;
       *) 
        echo "Uknown arguments, please  check the help : initdev –help"  
        exit 1
        esac
